[package]
name = "rockfetch"
version = "0.1.4"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-release = "0.1.7"

[build-dependencies]
toml = "0.5.8"
