## Infos ##
# Colors are either ANSI color codes (escape char is \u001B) or an array of rgb values [r, g, b].
# RGB colors are bold/bright by default, append an optional element to the array to use the normal variant (ex: [255, 255, 255, 1]).
# support for them depends on your terminal.
#
# In case of a missing setting (both in the theme an conf table) the hardcoded default will be used.
# If a value is left empty (ex: RESET = "") the value will stay empty.
# Please make sure to completely delete a value to use its hardcoded default.


# This is your main config, here you can set a theme and override its values
[conf]
#theme = "name"

#RESET  = ""      # You can use those values to override your current theme
#COLOR1 = []
#COLOR2 = []
#COLOR3 = []
#FONT1  = []
#FONT2  = []
#FONT3  = []



#[theme.name]     # (Uncomment this and use it as a model for your custom theme)

#RESET = ""

#COLOR1 = []
#COLOR2 = []
#COLOR3 = []

#FONT1 = []
#FONT2 = []
#FONT3 = []




#[theme.ample_coffee]     # (Uncomment this theme and set it in [conf]'s theme setting to use it)
#COLOR1 = [192, 103, 9] # Orange
#COLOR2 = [226, 78, 78] # Red
#COLOR3 = [226, 78, 78] # Red
#FONT1 = [226, 78, 78] # Red
#FONT2 = [192, 103, 9] # Orange
#FONT3 = [226, 78, 78] # Red
