[env]

## Infos ##
# Colors are simply ANSI color codes (escape char is \u001B)
# support for them depends on your terminal.
#
# In case of a missing setting the hardcoded default will be used.

#------------------------#

## Empty Colors ## (Uncomment this and use it as a model)

#RESET = ""

#C1 = ""
#C2 = ""

#FONT1 = ""
#FONT2 = ""
#FONT3 = ""

#------------------------#

## Ample/Coffee theme ## (Uncomment this palette to use it)

#C1 = "\u001B[0m\u001B[1;38;2;192;103;9m" # Orange
#C2 = "\u001B[0m\u001B[1;38;2;226;78;78m" # Red

#FONT1 = "\u001B[0m\u001B[1;38;2;226;78;78m" # Red
#FONT2 = "\u001B[0m\u001B[1;38;2;192;103;9m" # Orange
#FONT3 = "\u001B[0m\u001B[1;38;2;226;78;78m" # Red
